package com.lordjoe.loeb;

import java.util.HashMap;
import java.util.Map;

/**
 * com.lordjoe.loeb.FixEDUState
 * User: Steve
 * Date: 4/6/2018
 */
public class FixEDUState {

    private static Map<String, State> eduByState = new HashMap<>();

    public static String getDomain(String email) {
        if (!email.endsWith(".edu"))
            return email;
        String[] items = email.split("\\.");
        int length = items.length;
        if (length > 2) {
            String domain = items[length - 2] + ".edu";
            return domain;
        }
        return email;
    }

    public static void rememberEDUState(String email, State state) {
        if(state == State.UNKNOWN)
            return;
        State existing = eduByState.get(email);
        if(existing == state)
            return;
        if(existing != null  )
            eduByState.put(email, state); // break herte

         eduByState.put(email, state);
        String domain = getDomain(email);
        if (!domain.equalsIgnoreCase(email))
            eduByState.put(domain, state);
    }

    private static void buildEdyByState() {
         if(!eduByState.isEmpty())
             return;
        rememberEDUState("stac.edu", State.NEW_YORK);
        rememberEDUState("mycu.concord.edu", State.WEST_VIRGINIA);
        rememberEDUState("my.pfeiffer.edu", State.NORTH_CAROLINA);
        rememberEDUState("email.usc.edu", State.CALIFORNIA);
        rememberEDUState("alliant.edu", State.CALIFORNIA);
        rememberEDUState("eiu.edu", State.ILLINOIS);
        rememberEDUState("sju.edu", State.PENNSYLVANIA);
        rememberEDUState("robertmorris.edu", State.ILLINOIS);
        rememberEDUState("as.ua.edu", State.ALABAMA);
        rememberEDUState("acpub.duke.edu", State.NORTH_CAROLINA);
        rememberEDUState("hofstra.edu", State.NEW_YORK);
        rememberEDUState("washington.edu", State.WASHINGTON);
        rememberEDUState("marymount.edu", State.VIRGINIA);
        rememberEDUState("northpark.edu", State.ILLINOIS);
        rememberEDUState("utulsa.edu", State.OKLAHOMA);
        rememberEDUState("clcillinois.edu", State.ILLINOIS);
        rememberEDUState("law.stetson.edu", State.FLORIDA);
        rememberEDUState("zimbra.naz.edu", State.NEW_YORK);
        rememberEDUState("martinmethodist.edu", State.TENNESSEE);
        rememberEDUState("soc.utexas.edu", State.TEXAS);
        rememberEDUState("stmarytx.edu", State.TEXAS);
        rememberEDUState("midway.uchicago.edu", State.ILLINOIS);
        rememberEDUState("law.uoregon.edu", State.OREGON);
        rememberEDUState("contracosta.edu", State.CALIFORNIA);
        rememberEDUState("sunybroome.edu", State.NEW_YORK);
        rememberEDUState("mccombs.utexas.edu", State.TEXAS);
        rememberEDUState("lvc.edu", State.PENNSYLVANIA);
        rememberEDUState("wesley.edu", State.DELAWARE);
        rememberEDUState("ycp.edu", State.PENNSYLVANIA);
        rememberEDUState("mville.edu", State.NEW_YORK);
        rememberEDUState("marietta.edu", State.OHIO);
        rememberEDUState("mail.la.utexas.edu", State.TEXAS);
        rememberEDUState("lipscomb.edu", State.TENNESSEE);
        rememberEDUState("marian.edu", State.INDIANA);
        rememberEDUState("hawken.edu", State.OHIO);
        rememberEDUState("gac.edu", State.MINNESOTA);
        rememberEDUState("cn.edu", State.TENNESSEE);
        rememberEDUState("davisny.edu", State.NEW_YORK);
        rememberEDUState("alumni.williams.edu", State.MASSACHUSETTS);
        rememberEDUState("hanover.edu", State.INDIANA);
        rememberEDUState("mtmail.mtsu.edu", State.TENNESSEE);
        rememberEDUState("emmanuel.edu", State.MASSACHUSETTS);
        rememberEDUState("sage.edu", State.NEW_YORK);
        rememberEDUState("tompkinscortland.edu", State.NEW_YORK);
        rememberEDUState("cleveland.edu", State.OHIO);
        rememberEDUState("ghc.edu", State.WASHINGTON);
        rememberEDUState("sccnc.edu", State.NORTH_CAROLINA);
        rememberEDUState("ndscs.edu", State.NORTH_DAKOTA);
        rememberEDUState("salud.unm.edu", State.NEW_MEXICO);
        rememberEDUState("garnet.acns.fsu.edu", State.FLORIDA);
        rememberEDUState("mwcc.mass.edu", State.MASSACHUSETTS);
        rememberEDUState("stthomas.edu", State.MINNESOTA);
        rememberEDUState("cabrini.edu", State.PENNSYLVANIA);
        rememberEDUState("tusculum.edu", State.TENNESSEE);
        rememberEDUState("notes.cc.sunysb.edu", State.NEW_YORK);
        rememberEDUState("stolaf.edu", State.MINNESOTA);
        rememberEDUState("oznet.ksu.edu", State.KANSAS);
        rememberEDUState("macalester.edu", State.MINNESOTA);
        rememberEDUState("augie.edu", State.SOUTH_DAKOTA);
        rememberEDUState("iowacentral.edu", State.IOWA);
        rememberEDUState("daltonstate.edu", State.GEORGIA);
        rememberEDUState("jamessprunt.edu", State.NORTH_CAROLINA);
        rememberEDUState("wlc.edu", State.WISCONSIN);
        rememberEDUState("clemson.edu", State.SOUTH_CAROLINA);
        rememberEDUState("weber.edu", State.UTAH);
        rememberEDUState("mills.edu", State.CALIFORNIA);
        rememberEDUState("msmc.edu", State.NEW_YORK);
        rememberEDUState("defiance.edu", State.OHIO);
        rememberEDUState("usm.edu", State.MISSISSIPPI);
        rememberEDUState("utah.edu", State.UTAH);
        rememberEDUState("philosophy.utah.edu", State.UTAH);
        rememberEDUState("kwc.edu", State.KENTUCKY);
        rememberEDUState("lakemichigancollege.edu", State.MICHIGAN);
        rememberEDUState("swmich.edu", State.MICHIGAN);
        rememberEDUState("email.edcc.edu", State.WASHINGTON);
        rememberEDUState("canisius.edu", State.NEW_YORK);
        rememberEDUState("soc.ucsb.edu", State.CALIFORNIA);
        rememberEDUState("anderson.ucla.edu", State.CALIFORNIA);
        rememberEDUState("bryant.edu", State.RHODE_ISLAND);
        rememberEDUState("nwic.edu", State.WASHINGTON);
        rememberEDUState("crossroadscollege.edu", State.MINNESOTA);
        rememberEDUState("austincollege.edu", State.TEXAS);
        rememberEDUState("bakeru.edu", State.KANSAS);
        rememberEDUState("kettering.edu", State.MICHIGAN);
        rememberEDUState("fas.harvard.edu", State.MASSACHUSETTS);
        rememberEDUState("mail.ucf.edu", State.FLORIDA);
        rememberEDUState("cnr.edu", State.NEW_YORK);
        rememberEDUState("po.utexas.edu", State.TEXAS);
        rememberEDUState("ulm.edu", State.LOUISIANA);
        rememberEDUState("roberts.edu", State.NEW_YORK);
        rememberEDUState("stanly.edu", State.NORTH_CAROLINA);
        rememberEDUState("aucegypt.edu", State.OVERSEAS);
        rememberEDUState("hamline.edu", State.MINNESOTA);
        rememberEDUState("prairiestate.edu", State.ILLINOIS);
        rememberEDUState("smumn.edu", State.MINNESOTA);
        rememberEDUState("grandview.edu", State.IOWA);
        rememberEDUState("iuk.edu", State.INDIANA);
        rememberEDUState("iit.edu", State.ILLINOIS);
        rememberEDUState("mso.umt.edu", State.MONTANA);
        rememberEDUState("wagner.edu", State.NEW_YORK);
        rememberEDUState("sycamores.indstate.edu", State.INDIANA);
        rememberEDUState("leland.stanford.edu", State.CALIFORNIA);
        rememberEDUState("thomasmore.edu", State.KENTUCKY);
        rememberEDUState("aquinas.edu", State.MICHIGAN);
        rememberEDUState("cs.cmu.edu", State.PENNSYLVANIA);
        rememberEDUState("donnelly.edu", State.KANSAS);
        rememberEDUState("stat.stanford.edu", State.CALIFORNIA);
        rememberEDUState("che.umn.edu", State.NEW_MEXICO);
        rememberEDUState("easternct.edu", State.CONNECTICUT);
        rememberEDUState("lake.ollusa.edu", State.TEXAS);
        rememberEDUState("ucsd.edu", State.CALIFORNIA);
        rememberEDUState("arecibo.inter.edu", State.PUERTO_RICO);
        rememberEDUState("mail.clayton.edu", State.GEORGIA);
        rememberEDUState("pols.acu.edu", State.TEXAS);
        rememberEDUState("wsc.edu", State.NEBRASKA);
        rememberEDUState("cccs.cccoes.edu", State.UNKNOWN);     // bad
        rememberEDUState("norwich.edu", State.VERMONT);
        rememberEDUState("psg.ucsf.edu", State.CALIFORNIA);
        rememberEDUState("gccaz.edu", State.ARIZONA);
        rememberEDUState("huhezi.edu", State.UNKNOWN);
        rememberEDUState("trinity.edu", State.DISTRICT_OF_COLUMBIA);
        rememberEDUState("phsc.edu", State.FLORIDA);
        rememberEDUState("mizzou.edu", State.MISSOURI);
        rememberEDUState("lfc.edu", State.VIRGINIA);
        rememberEDUState("case.edu", State.OHIO);
        rememberEDUState("wsc.ma.edu", State.MASSACHUSETTS);
        rememberEDUState("email.stvincent.edu", State.PENNSYLVANIA);
        rememberEDUState("centralstate.edu", State.OHIO);
        rememberEDUState("sjsu.edu", State.CALIFORNIA);
        rememberEDUState("pia.edu", State.PENNSYLVANIA);
        rememberEDUState("physics.ucsc.edu", State.CALIFORNIA);
        rememberEDUState("neo.edu", State.OKLAHOMA);
        rememberEDUState("maroon.tc.umn.edu", State.NEW_MEXICO);
        rememberEDUState("hks.harvard.edu", State.MASSACHUSETTS);
        rememberEDUState("eohsi.rutgers.edu", State.NEW_JERSEY);
        rememberEDUState("otterbein.edu", State.OHIO);
        rememberEDUState("mtsac.edu", State.CALIFORNIA);
        rememberEDUState("wartburgseminary.edu", State.IOWA);
        rememberEDUState("morehead-st.edu", State.KENTUCKY);
        rememberEDUState("minnesota.edu", State.MINNESOTA);
        rememberEDUState("mcc.edu", State.MICHIGAN);
        rememberEDUState("exchange.upenn.edu", State.PENNSYLVANIA);
        rememberEDUState("asub.edu", State.ARKANSAS);
        rememberEDUState("uhcl.edu", State.TEXAS);
        rememberEDUState("soe.gonzaga.edu", State.WASHINGTON);
        rememberEDUState("knox.edu", State.ILLINOIS);
        rememberEDUState("adm.gogebic.edu", State.MICHIGAN);
        rememberEDUState("cslanet.calstatela.edu", State.CALIFORNIA);
        rememberEDUState("coppin.edu", State.MARYLAND);
        rememberEDUState("crimson.ua.edu", State.ALABAMA);
        rememberEDUState("siskiyous.edu", State.CALIFORNIA);
        rememberEDUState("my.unt.edu", State.TEXAS);
        rememberEDUState("sociology.rutgers.edu", State.NEW_JERSEY);
        rememberEDUState("qc.edu", State.NEW_YORK);
        rememberEDUState("stonybrook.edu", State.NEW_YORK);
        rememberEDUState("miracosta.edu", State.CALIFORNIA);
        rememberEDUState("hms.harvard.edu", State.MASSACHUSETTS);
        rememberEDUState("rustcollege.edu", State.MISSISSIPPI);
        rememberEDUState("mcc.commnet.edu", State.CONNECTICUT);
        rememberEDUState("davidsonccc.edu", State.NORTH_CAROLINA);
        rememberEDUState("scott.skidmore.edu", State.NEW_YORK);
        rememberEDUState("mymail.nku.edu", State.KENTUCKY);
        rememberEDUState("sit.edu", State.VERMONT);
        rememberEDUState("newberry.edu", State.SOUTH_CAROLINA);
        rememberEDUState("lccc.edu", State.PENNSYLVANIA);
        rememberEDUState("pubpol.umass.edu", State.MASSACHUSETTS);
        rememberEDUState("mtu.edu", State.MICHIGAN);
        rememberEDUState("acis32.admin.ccny.cuny.edu", State.NEW_YORK);
        rememberEDUState("vtc.vsc.edu", State.VERMONT);
        rememberEDUState("up.edu", State.OREGON);
        rememberEDUState("comm.ucsb.edu", State.CALIFORNIA);
        rememberEDUState("strayer.edu", State.VIRGINIA);
        rememberEDUState("converse.edu", State.SOUTH_CAROLINA);
        rememberEDUState("english.umass.edu", State.MASSACHUSETTS);
        rememberEDUState("union.edu", State.NEW_YORK);
        rememberEDUState("nfcc.edu", State.FLORIDA);
        rememberEDUState("greensboro.edu", State.VIRGINIA);
        rememberEDUState("presby.edu", State.DISTRICT_OF_COLUMBIA);
        rememberEDUState("comm.umass.edu", State.MASSACHUSETTS);
        rememberEDUState("suny.edu", State.NEW_YORK);
        rememberEDUState("alumni.usc.edu", State.CALIFORNIA);
        rememberEDUState("mail.fairfield.edu", State.CONNECTICUT);
        rememberEDUState("lhup.edu", State.PENNSYLVANIA);
        rememberEDUState("nichols.edu", State.MASSACHUSETTS);
        rememberEDUState("menlo.edu", State.CALIFORNIA);
        rememberEDUState("emu.edu", State.MICHIGAN);
        rememberEDUState("gloria.cord.edu", State.MINNESOTA);
        rememberEDUState("usip.edu", State.PENNSYLVANIA);
        rememberEDUState("punahou.edu", State.HAWAII);
        rememberEDUState("blc.edu", State.MINNESOTA);
        rememberEDUState("misericordia.edu", State.PENNSYLVANIA);
        rememberEDUState("brenau.edu", State.GEORGIA);
        rememberEDUState("davenport.edu", State.MICHIGAN);
        rememberEDUState("maryvillecollege.edu", State.TENNESSEE);
        rememberEDUState("stlawu.edu", State.NEW_YORK);
        rememberEDUState("ysu.edu", State.OHIO);
        rememberEDUState("msmnyc.edu", State.NEW_YORK);
        rememberEDUState("mit.edu", State.MASSACHUSETTS);
        rememberEDUState("normandale.edu", State.MINNESOTA);
        rememberEDUState("ancilla.edu", State.INDIANA);
        rememberEDUState("montcalm.edu", State.MICHIGAN);
        rememberEDUState("uwsuper.edu", State.WISCONSIN);
        rememberEDUState("eservices.virginia.edu", State.VIRGINIA);
        rememberEDUState("austincc.edu", State.TEXAS);
        rememberEDUState("ottawa.edu", State.KANSAS);
        rememberEDUState("live.missouristate.edu", State.MISSOURI);
        rememberEDUState("nyit.edu", State.NEW_YORK);
        rememberEDUState("tc.edu", State.NEW_YORK);
        rememberEDUState("mr.mnscu.edu", State.MINNESOTA);
        rememberEDUState("ksg.harvard.edu", State.MASSACHUSETTS);
        rememberEDUState("downstate.edu", State.NEW_YORK);
        rememberEDUState("columbustech.edu", State.GEORGIA);
        rememberEDUState("tch.harvard.edu", State.MASSACHUSETTS);
        rememberEDUState("stmary.edu", State.KANSAS);
        rememberEDUState("gw.hamline.edu", State.MINNESOTA);
        rememberEDUState("su.edu", State.VIRGINIA);
        rememberEDUState("alumni.princeton.edu", State.NEW_JERSEY);
        rememberEDUState("culver.edu", State.MISSOURI);
        rememberEDUState("uc.syr.edu", State.NEW_YORK);
        rememberEDUState("cc.owu.edu", State.OHIO);
        rememberEDUState("hrsm.sc.edu", State.SOUTH_CAROLINA);
        rememberEDUState("limestone.edu", State.SOUTH_CAROLINA);
        rememberEDUState("jsu.edu", State.ALABAMA);
        rememberEDUState("southwestern.edu", State.TEXAS);
        rememberEDUState("susqu.edu", State.PENNSYLVANIA);
        rememberEDUState("lasierra.edu", State.CALIFORNIA);
        rememberEDUState("soc.umass.edu", State.MASSACHUSETTS);
        rememberEDUState("english.ufl.edu", State.FLORIDA);
        rememberEDUState("puc.edu", State.CALIFORNIA);
        rememberEDUState("rush.edu", State.ILLINOIS);
        rememberEDUState("greenriver.edu", State.WASHINGTON);
        rememberEDUState("northwood.edu", State.MICHIGAN);
        rememberEDUState("grcc.edu", State.MICHIGAN);
        rememberEDUState("mineralarea.edu", State.MISSOURI);
        rememberEDUState("bentley.edu", State.MASSACHUSETTS);
        rememberEDUState("sdsu.edu", State.CALIFORNIA);
        rememberEDUState("whs.edu", State.UNKNOWN);
        rememberEDUState("saintleo.edu", State.FLORIDA);
        rememberEDUState("owens.edu", State.OHIO);
        rememberEDUState("mercury.hendrix.edu", State.ARKANSAS);
        rememberEDUState("reedleycollege.edu", State.CALIFORNIA);
        rememberEDUState("tc.umn.edu", State.MINNESOTA);
        rememberEDUState("cahs.colostate.edu", State.COLORADO);
        rememberEDUState("media.utah.edu", State.UTAH);
        rememberEDUState("amherst.edu", State.MASSACHUSETTS);
        rememberEDUState("cayuga-cc.edu", State.NEW_YORK);
        rememberEDUState("wm.edu", State.VIRGINIA);
        rememberEDUState("law.vanderbilt.edu", State.TENNESSEE);
        rememberEDUState("weatherhead.cwru.edu", State.OHIO);
        rememberEDUState("whoi.edu", State.MASSACHUSETTS);
        rememberEDUState("bush.edu", State.WASHINGTON);
        rememberEDUState("northgeorgia.edu", State.GEORGIA);
        rememberEDUState("mscok.edu", State.OKLAHOMA);
        rememberEDUState("wvu.edu", State.WEST_VIRGINIA);
        rememberEDUState("stephens.edu", State.MISSOURI);
        rememberEDUState("assumption.edu", State.MASSACHUSETTS);
        rememberEDUState("byu.edu", State.UTAH);
        rememberEDUState("sc4.edu", State.MICHIGAN);
        rememberEDUState("kvcc.edu", State.MICHIGAN);
        rememberEDUState("nebrwesleyan.edu", State.NEBRASKA);
        rememberEDUState("email.wcu.edu", State.NORTH_CAROLINA);
        rememberEDUState("smccme.edu", State.MAINE);
        rememberEDUState("northland.edu", State.WISCONSIN);
        rememberEDUState("bsos.umd.edu", State.MARYLAND);
        rememberEDUState("carleton.edu", State.MINNESOTA);
        rememberEDUState("mailbox.syr.edu", State.NEW_YORK);
        rememberEDUState("regis.edu", State.COLORADO);
        rememberEDUState("whitman.edu", State.WASHINGTON);
        rememberEDUState("world.oberlin.edu", State.OHIO);
        rememberEDUState("southside.edu", State.VIRGINIA  );
        rememberEDUState("pvamu.edu", State.TEXAS);
        rememberEDUState("newschool.edu", State.NEW_YORK);
        rememberEDUState("ouhsc.edu", State.OKLAHOMA);
        rememberEDUState("tccd.edu", State.TEXAS);
        rememberEDUState("coe.ttu.edu", State.TEXAS);
        rememberEDUState("medaille.edu", State.NEW_YORK);
        rememberEDUState("ccm.edu", State.NEW_JERSEY);
        rememberEDUState("ucmo.edu", State.MISSOURI);
        rememberEDUState("salemcc.edu", State.NEW_JERSEY);
        rememberEDUState("rice.edu", State.TEXAS);
        rememberEDUState("mail.rochester.edu", State.NEW_YORK);
        rememberEDUState("deltastate.edu", State.MISSISSIPPI);
        rememberEDUState("umd.umich.edu", State.MICHIGAN);
        rememberEDUState("ovu.edu", State.OHIO);
        rememberEDUState("mnsfld.edu", State.PENNSYLVANIA);
        rememberEDUState("western.edu", State.COLORADO);
        rememberEDUState("lorainccc.edu", State.OHIO);
        rememberEDUState("ircs.edu", State.FLORIDA);
        rememberEDUState("cccd.edu", State.COLORADO);
        rememberEDUState("exchange.fullerton.edu", State.CALIFORNIA);
        rememberEDUState("talladega.edu", State.ALABAMA);
        rememberEDUState("admin.umass.edu", State.MASSACHUSETTS);
        rememberEDUState("dance.fsu.edu", State.FLORIDA);
        rememberEDUState("princeton.edu", State.NEW_JERSEY);
        rememberEDUState("wolfmail.stritch.edu", State.WISCONSIN);
        rememberEDUState("trincoll.edu", State.CONNECTICUT);
        rememberEDUState("heidelberg.edu", State.OHIO);
        rememberEDUState("scrippscol.edu", State.CALIFORNIA);
        rememberEDUState("cwru.edu", State.OHIO);
        rememberEDUState("ohiou.edu", State.OHIO);
        rememberEDUState("isu.edu", State.IDAHO);
        rememberEDUState("lsua.edu", State.LOUISIANA);
        rememberEDUState("bvu.edu", State.IOWA);
        rememberEDUState("csum.edu", State.CALIFORNIA);
        rememberEDUState("byui.edu", State.IDAHO);
        rememberEDUState("hamlineuniversity.edu", State.MINNESOTA);
        rememberEDUState("rocky.edu", State.MONTANA);
        rememberEDUState("soli.cord.edu", State.MINNESOTA);
        rememberEDUState("bealcollege.edu", State.MAINE);
        rememberEDUState("und.nodak.edu", State.NORTH_DAKOTA);
        rememberEDUState("apu.edu", State.CALIFORNIA);
        rememberEDUState("hamilton.edu", State.NEW_YORK);
        rememberEDUState("marauder.millersv.edu", State.PENNSYLVANIA);
        rememberEDUState("usiouxfalls.edu", State.SOUTH_DAKOTA);
        rememberEDUState("alumni.ufl.edu", State.FLORIDA);
        rememberEDUState("holycross.edu", State.MASSACHUSETTS);
        rememberEDUState("ramapo.edu", State.NEW_JERSEY);
        rememberEDUState("udc.edu", State.DISTRICT_OF_COLUMBIA);
        rememberEDUState("musc.edu", State.SOUTH_CAROLINA);
        rememberEDUState("sdsmt.edu", State.SOUTH_DAKOTA);
        rememberEDUState("naicu.edu", State.UNKNOWN);
        rememberEDUState("medicine.ucsf.edu", State.CALIFORNIA);
        rememberEDUState("library.berkeley.edu", State.CALIFORNIA);
        rememberEDUState("haskell.edu", State.KANSAS);
        rememberEDUState("claremontmckenna.edu", State.CALIFORNIA);
        rememberEDUState("jhmi.edu", State.MARYLAND);
        rememberEDUState("semovm.semo.edu", State.MISSOURI);
        rememberEDUState("mckendree.edu", State.ILLINOIS);
        rememberEDUState("nsu.nova.edu", State.FLORIDA);
        rememberEDUState("lyndonstate.edu", State.VERMONT);
        rememberEDUState("dscc.edu", State.TENNESSEE);
        rememberEDUState("kysu.edu", State.KENTUCKY);
        rememberEDUState("acsu.buffalo.edu", State.NEW_JERSEY);
        rememberEDUState("hampshire.edu", State.MASSACHUSETTS);
        rememberEDUState("vassar.edu", State.NEW_YORK);
        rememberEDUState("mail.lesley.edu", State.MASSACHUSETTS);
        rememberEDUState("ubalt.edu", State.MARYLAND);
        rememberEDUState("darwin.stanford.edu", State.CALIFORNIA);
        rememberEDUState("vanguard.edu", State.CALIFORNIA);
        rememberEDUState("utpb.edu", State.TEXAS);
        rememberEDUState("carthage.edu", State.WISCONSIN);
        rememberEDUState("westga.edu", State.GEORGIA);
        rememberEDUState("oberlin.edu", State.OHIO);
        rememberEDUState("fa.ua.edu", State.ALABAMA);
        rememberEDUState("bumail.bradley.edu", State.ILLINOIS);
        rememberEDUState("quincycollege.edu", State.MASSACHUSETTS);
        rememberEDUState("rossier.usc.edu", State.CALIFORNIA);
        rememberEDUState("student.wpunj.edu", State.NEW_JERSEY);
        rememberEDUState("gse.upenn.edu", State.PENNSYLVANIA);
        rememberEDUState("mail.colgate.edu", State.NEW_YORK);
        rememberEDUState("hum.utah.edu", State.UTAH);
        rememberEDUState("mtso.edu", State.OHIO);
        rememberEDUState("dartmouth.edu", State.NEW_HAMPSHIRE);
        rememberEDUState("hhh.umn.edu", State.NEW_MEXICO);
        rememberEDUState("walton.uark.edu", State.ARKANSAS);
        rememberEDUState("catawba.edu", State.NORTH_CAROLINA);
        rememberEDUState("northwestern.edu", State.ILLINOIS);
        rememberEDUState("coa.edu", State.NORTH_CAROLINA);
        rememberEDUState("email.uophx.edu", State.UNKNOWN);        // bad
        rememberEDUState("wilson.edu", State.PENNSYLVANIA);
        rememberEDUState("cbts.edu", State.UNKNOWN);        // bad
        rememberEDUState("mcw.edu", State.WISCONSIN);
        rememberEDUState("antiochsea.edu", State.WASHINGTON);
        rememberEDUState("umext.umass.edu", State.MASSACHUSETTS);
        rememberEDUState("email.smith.edu", State.MASSACHUSETTS);
        rememberEDUState("strom.clemson.edu", State.SOUTH_CAROLINA);
        rememberEDUState("central.uh.edu", State.TEXAS);
        rememberEDUState("college.occc.edu", State.OKLAHOMA);
        rememberEDUState("brynmawr.edu", State.PENNSYLVANIA);
        rememberEDUState("sunyacc.edu", State.NEW_YORK);
        rememberEDUState("kzoo.edu", State.MICHIGAN);
        rememberEDUState("max.cc.denison.edu", State.OHIO);
        rememberEDUState("mesacc.edu", State.ARIZONA);
        rememberEDUState("tiptoe.fhda.edu", State.CALIFORNIA);
        rememberEDUState("stpt.usf.edu", State.FLORIDA);
        rememberEDUState("usma.edu", State.NEW_YORK);
        rememberEDUState("cc.ysu.edu", State.OHIO);
        rememberEDUState("sa.ucsb.edu", State.CALIFORNIA);
        rememberEDUState("herkimer.edu", State.NEW_YORK);
        rememberEDUState("ciis.edu", State.CALIFORNIA);
        rememberEDUState("ups.edu", State.WASHINGTON);
        rememberEDUState("socwk.utah.edu", State.UTAH);
        rememberEDUState("regiscollege.edu", State.MASSACHUSETTS);
        rememberEDUState("lsus.edu", State.LOUISIANA);
        rememberEDUState("wlu.edu", State.VIRGINIA);
        rememberEDUState("hmc.edu", State.CALIFORNIA);
        rememberEDUState("dominican.edu", State.CALIFORNIA);
        rememberEDUState("hsu.edu", State.ARKANSAS);
        rememberEDUState("sbu.edu", State.NEW_YORK);
        rememberEDUState("felician.edu", State.NEW_JERSEY);
        rememberEDUState("mailbox.mail.umn.edu", State.NEW_MEXICO);
        rememberEDUState("kellogg.edu", State.MICHIGAN);
        rememberEDUState("aurora.edu", State.ILLINOIS);
        rememberEDUState("law.ufl.edu", State.FLORIDA);
        rememberEDUState("robotics.stanford.edu", State.CALIFORNIA);
        rememberEDUState("ollusa.edu", State.TEXAS);
        rememberEDUState("benedictine.edu", State.KANSAS);
        rememberEDUState("wnmu.edu", State.NEW_MEXICO);
        rememberEDUState("toto.csustan.edu", State.CALIFORNIA);
        rememberEDUState("sullivan.suny.edu", State.NEW_YORK);
        rememberEDUState("fpu.edu", State.CALIFORNIA);
        rememberEDUState("mail.sunyjcc.edu", State.NEW_YORK);
        rememberEDUState("bloomu.edu", State.PENNSYLVANIA);
        rememberEDUState("chancellor.umass.edu", State.MASSACHUSETTS);
        rememberEDUState("mtmary.edu", State.WISCONSIN);
        rememberEDUState("moravian.edu", State.PENNSYLVANIA);
        rememberEDUState("agnesscott.edu", State.GEORGIA);
        rememberEDUState("miami.edu", State.FLORIDA);
        rememberEDUState("william.jewell.edu", State.MISSOURI);
        rememberEDUState("sa.ua.edu", State.ALABAMA);
        rememberEDUState("bcc.orst.edu", State.OREGON);
        rememberEDUState("mail.csuchico.edu", State.CALIFORNIA);
        rememberEDUState("graceland.edu", State.IOWA);
        rememberEDUState("coba.usf.edu", State.FLORIDA);
        rememberEDUState("iusb.edu", State.INDIANA);
        rememberEDUState("wpcc.edu", State.NORTH_CAROLINA);
        rememberEDUState("harvard.edu", State.MASSACHUSETTS);
        rememberEDUState("wju.edu", State.WEST_VIRGINIA);
        rememberEDUState("surry.edu", State.NORTH_CAROLINA);
        rememberEDUState("clayton.edu", State.GEORGIA);
        rememberEDUState("slc.edu", State.NEW_YORK);
        rememberEDUState("sarahlawrence.edu", State.NEW_YORK);
        rememberEDUState("wellesley.edu", State.MASSACHUSETTS);
        rememberEDUState("mayo.edu", State.UNKNOWN);        // bad
        rememberEDUState("cesl.umass.edu", State.MASSACHUSETTS);
        rememberEDUState("wvc.edu", State.WASHINGTON);
        rememberEDUState("mail.umd.edu", State.MARYLAND);
        rememberEDUState("concordia.edu", State.TEXAS);
        rememberEDUState("lincolnu.edu", State.MISSOURI);
        rememberEDUState("alumni.brown.edu", State.RHODE_ISLAND);
        rememberEDUState("mail.smu.edu", State.TEXAS);
        rememberEDUState("manhattan.edu", State.NEW_YORK);
        rememberEDUState("mail.etsu.edu", State.TENNESSEE);
        rememberEDUState("iliff.edu", State.COLORADO);
        rememberEDUState("park.edu", State.MISSOURI);
        rememberEDUState("wcl.american.edu", State.DISTRICT_OF_COLUMBIA);
        rememberEDUState("cats.ucsc.edu", State.CALIFORNIA);
        rememberEDUState("elon.edu", State.NORTH_CAROLINA);
        rememberEDUState("xu.edu", State.OHIO);
        rememberEDUState("caldwell.edu", State.NEW_JERSEY);
        rememberEDUState("omed.gatech.edu", State.GEORGIA);
        rememberEDUState("bellevue.edu", State.NEBRASKA);
        rememberEDUState("lstc.edu", State.ILLINOIS);
        rememberEDUState("andover.edu", State.MASSACHUSETTS);
        rememberEDUState("domail.maricopa.edu", State.ARIZONA);
        rememberEDUState("saybrook.edu", State.CALIFORNIA);
        rememberEDUState("flsouthern.edu", State.FLORIDA);
        rememberEDUState("darkwing.uoregon.edu", State.OREGON);
        rememberEDUState("esue.ohio-state.edu", State.OHIO);
        rememberEDUState("uop.edu", State.UNKNOWN);      // bad
        rememberEDUState("uwlax.edu", State.WISCONSIN);
        rememberEDUState("lklnd.usf.edu", State.CALIFORNIA);
        rememberEDUState("morainevalley.edu", State.ILLINOIS);
        rememberEDUState("cs.stanford.edu", State.CALIFORNIA);
        rememberEDUState("winthrop.edu", State.SOUTH_CAROLINA);
        rememberEDUState("emerald.tufts.edu", State.MASSACHUSETTS);
        rememberEDUState("uamont.edu", State.ARKANSAS);
        rememberEDUState("runet.edu", State.VIRGINIA);
        rememberEDUState("notes.udayton.edu", State.OHIO);
        rememberEDUState("lsps.edu", State.ILLINOIS);
        rememberEDUState("tcu.edu", State.TEXAS);
        rememberEDUState("tmcc.edu", State.NEVADA);
        rememberEDUState("facstaff.wisc.edu", State.WISCONSIN);
        rememberEDUState("meredith.edu", State.NORTH_CAROLINA);
        rememberEDUState("cumberland.edu", State.TENNESSEE);
        rememberEDUState("cnu.edu", State.VIRGINIA);
        rememberEDUState("arches.uga.edu", State.GEORGIA);
        rememberEDUState("go.wpcc.edu", State.NORTH_CAROLINA);
        rememberEDUState("ecok.edu", State.OKLAHOMA);
        rememberEDUState("westliberty.edu", State.VIRGINIA);
        rememberEDUState("austin.utexas.edu", State.TEXAS);
        rememberEDUState("armstrong.edu", State.GEORGIA);
        rememberEDUState("alaska.edu", State.ALASKA);
        rememberEDUState("lamar.colostate.edu", State.COLORADO);
        rememberEDUState("grayson.edu", State.TEXAS);
        rememberEDUState("fandm.edu", State.PENNSYLVANIA);
        rememberEDUState("eureka.edu", State.ILLINOIS);
        rememberEDUState("phoenixcollege.edu", State.ARIZONA);
        rememberEDUState("cornellcollege.edu", State.NEW_YORK);
        rememberEDUState("lawrence.edu", State.WISCONSIN);
        rememberEDUState("iue.edu", State.INDIANA);
        rememberEDUState("egcc.edu", State.OHIO);
        rememberEDUState("science.oregonstate.edu", State.OREGON);
        rememberEDUState("longwood.edu", State.VIRGINIA);
        rememberEDUState("postoffice.providence.edu", State.RHODE_ISLAND);
        rememberEDUState("mailbox.une.edu", State.MAINE);
        rememberEDUState("loyno.edu", State.LOUISIANA);
        rememberEDUState("uwex.edu", State.WISCONSIN);
        rememberEDUState("transy.edu", State.KENTUCKY);
        rememberEDUState("glenoaks.edu", State.MICHIGAN);
        rememberEDUState("laredo.edu", State.TEXAS);
        rememberEDUState("gc.edu", State.TEXAS);
        rememberEDUState("duke.poly.edu", State.NORTH_CAROLINA);
        rememberEDUState("cloud.edu", State.KANSAS);
        rememberEDUState("ccsf.edu", State.CALIFORNIA);
        rememberEDUState("mu.edu", State.WISCONSIN);
        rememberEDUState("topper.wku.edu", State.KENTUCKY);
        rememberEDUState("ringling.edu", State.FLORIDA);
        rememberEDUState("mtech.edu", State.MONTANA);
        rememberEDUState("iowalakes.edu", State.IOWA);
        rememberEDUState("hws.edu", State.NEW_YORK);
        rememberEDUState("leeuniversity.edu", State.TENNESSEE);
        rememberEDUState("calvin.edu", State.MICHIGAN);
        rememberEDUState("gallaudet.edu", State.DISTRICT_OF_COLUMBIA);
        rememberEDUState("mail.barry.edu", State.FLORIDA);
        rememberEDUState("sunyit.edu", State.NEW_YORK);
        rememberEDUState("oxy.edu", State.CALIFORNIA);
        rememberEDUState("law.uiuc.edu", State.ILLINOIS);
        rememberEDUState("gettysburg.edu", State.PENNSYLVANIA);
        rememberEDUState("pluto.dsu.edu", State.SOUTH_CAROLINA);
        rememberEDUState("uwrf.edu", State.WISCONSIN);
        rememberEDUState("mail.ewu.edu", State.WASHINGTON);
        rememberEDUState("rit.edu", State.NEW_YORK);
        rememberEDUState("exploratorium.edu", State.CALIFORNIA);
        rememberEDUState("u.arizona.edu", State.ARIZONA);
        rememberEDUState("ashland.edu", State.OHIO);
        rememberEDUState("ls.wisc.edu", State.WISCONSIN);
        rememberEDUState("smu.edu", State.TEXAS);
        rememberEDUState("brynathyn.edu", State.PENNSYLVANIA);
        rememberEDUState("anthro.umass.edu", State.MASSACHUSETTS);
        rememberEDUState("socrates.berkeley.edu", State.CALIFORNIA);
        rememberEDUState("stthom.edu", State.TEXAS);
        rememberEDUState("cgcmail.maricopa.edu", State.ARIZONA);
        rememberEDUState("ucmail.uc.edu", State.CALIFORNIA);
        rememberEDUState("ccv.vsc.edu", State.VERMONT);
        rememberEDUState("post.harvard.edu", State.MASSACHUSETTS);
        rememberEDUState("spu.edu", State.WASHINGTON);
        rememberEDUState("ucsc.edu", State.CALIFORNIA);
        rememberEDUState("otc.edu", State.MISSOURI);
        rememberEDUState("gold.tc.umn.edu", State.NEW_MEXICO);
        rememberEDUState("lycoming.edu", State.PENNSYLVANIA);
        rememberEDUState("rutgers.edu", State.NEW_JERSEY);
        rememberEDUState("georgefox.edu", State.OREGON);
        rememberEDUState("mail.slc.edu", State.NEW_YORK);
        rememberEDUState("samford.edu", State.ALABAMA);
        rememberEDUState("law.byu.edu", State.UTAH);
        rememberEDUState("cuny.edu", State.NEW_YORK);
        rememberEDUState("bennington.edu", State.VERMONT);
        rememberEDUState("bowdoin.edu", State.MAINE);
        rememberEDUState("stgregorys.edu", State.OKLAHOMA);
        rememberEDUState("housing.ucsb.edu", State.CALIFORNIA);
        rememberEDUState("csudh.edu", State.CALIFORNIA);
        rememberEDUState("uidaho.edu", State.IDAHO);
        rememberEDUState("mail.millikin.edu", State.ILLINOIS);
        rememberEDUState("drew.edu", State.NEW_JERSEY);
        rememberEDUState("ju.edu", State.FLORIDA);
        rememberEDUState("sa.utah.edu", State.UTAH);
        rememberEDUState("alumni.nmu.edu", State.NEW_MEXICO);
        rememberEDUState("presidio.edu", State.CALIFORNIA);
        rememberEDUState("mail.law.ucla.edu", State.CALIFORNIA);
        rememberEDUState("fmlh.edu", State.WISCONSIN);
        rememberEDUState("bsc.edu", State.ALABAMA);
        rememberEDUState("wou.edu", State.OREGON);
        rememberEDUState("gatech.edu", State.GEORGIA);
        rememberEDUState("my.tccd.edu", State.TEXAS);
        rememberEDUState("stritch.edu", State.WISCONSIN);
        rememberEDUState("stmarys-ca.edu", State.CALIFORNIA);
        rememberEDUState("gladstone.uoregon.edu", State.OREGON);
        rememberEDUState("tricity.wsu.edu", State.WASHINGTON);
        rememberEDUState("fdu.edu", State.NEW_JERSEY);
        rememberEDUState("msx.umsl.edu", State.MISSOURI);
        rememberEDUState("mcmail.maricopa.edu", State.ARIZONA);
        rememberEDUState("eastms.edu", State.MISSISSIPPI);
        rememberEDUState("salem.edu", State.NORTH_CAROLINA);
        rememberEDUState("calvin.gonzaga.edu", State.WASHINGTON);
        rememberEDUState("davidson.edu", State.NORTH_CAROLINA);
        rememberEDUState("cpcc.edu", State.NORTH_CAROLINA);
        rememberEDUState("keuka.edu", State.NEW_YORK);
        rememberEDUState("newmoodle.wosc.edu", State.OKLAHOMA);
        rememberEDUState("bowiestate.edu", State.MARYLAND);
        rememberEDUState("oaklandcc.edu", State.CALIFORNIA);
        rememberEDUState("lists.stanford.edu", State.CALIFORNIA);
        rememberEDUState("gc.cuny.edu", State.NEW_YORK);
        rememberEDUState("alpha.lasalle.edu", State.PENNSYLVANIA);
        rememberEDUState("unex.berkeley.edu", State.CALIFORNIA);
        rememberEDUState("em.cortland.edu", State.NEW_YORK);
        rememberEDUState("lahc.edu", State.CALIFORNIA);
        rememberEDUState("martin.luther.edu", State.IOWA);
        rememberEDUState("sckans.edu", State.KANSAS);
        rememberEDUState("qcunix1.qc.edu", State.NEW_YORK);
        rememberEDUState("fairmontstate.edu", State.WEST_VIRGINIA);
        rememberEDUState("rcc.edu", State.CALIFORNIA);
        rememberEDUState("hts.gatech.edu", State.GEORGIA);
        rememberEDUState("txwes.edu", State.TEXAS);
        rememberEDUState("sbcc.edu", State.CALIFORNIA);
        rememberEDUState("sas.upenn.edu", State.PENNSYLVANIA);
        rememberEDUState("cuchicago.edu", State.ILLINOIS);
        rememberEDUState("stkate.edu", State.MINNESOTA);
        rememberEDUState("vermontlaw.edu", State.VERMONT);
        rememberEDUState("cf.edu", State.FLORIDA);
        rememberEDUState("goshen.edu", State.INDIANA);
        rememberEDUState("csli.stanford.edu", State.CALIFORNIA);
        rememberEDUState("carrollu.edu", State.WISCONSIN);
        rememberEDUState("brevard.edu", State.NORTH_CAROLINA);
        rememberEDUState("rivier.edu", State.NEW_HAMPSHIRE);
        rememberEDUState("wesleyan.edu", State.CONNECTICUT);
        rememberEDUState("northwestu.edu", State.WASHINGTON);
        rememberEDUState("desales.edu", State.PENNSYLVANIA);
        rememberEDUState("uafs.edu", State.ARKANSAS);
        rememberEDUState("flint.umich.edu", State.MICHIGAN);
        rememberEDUState("msmu.edu", State.CALIFORNIA);
        rememberEDUState("my.lonestar.edu", State.TEXAS);
        rememberEDUState("sunycgcc.edu", State.NEW_YORK);
        rememberEDUState("frederick.edu", State.MARYLAND);
        rememberEDUState("gcsu.edu", State.GEORGIA);
        rememberEDUState("southwest.tn.edu", State.TENNESSEE);
        rememberEDUState("acu.edu", State.TEXAS);
        rememberEDUState("mica.edu", State.MARYLAND);
        rememberEDUState("selu.edu", State.LOUISIANA);
        rememberEDUState("saintmarys.edu", State.INDIANA);
        rememberEDUState("mcla.edu", State.MASSACHUSETTS);
        rememberEDUState("mines.edu", State.COLORADO);
        rememberEDUState("law.howard.edu", State.DISTRICT_OF_COLUMBIA);
        rememberEDUState("as.ucsb.edu", State.CALIFORNIA);
        rememberEDUState("holyfamily.edu", State.PENNSYLVANIA);
        rememberEDUState("santarosa.edu", State.CALIFORNIA);
        rememberEDUState("sierranevada.edu", State.NEVADA);
        rememberEDUState("grove.iup.edu", State.PENNSYLVANIA);
        rememberEDUState("orst.edu", State.OREGON);
        rememberEDUState("mail1.vcu.edu", State.VIRGINIA);
        rememberEDUState("msoe.edu", State.WISCONSIN);
        rememberEDUState("swic.edu", State.ILLINOIS);
        rememberEDUState("columbusstate.edu", State.GEORGIA);
        rememberEDUState("pomona.edu", State.CALIFORNIA);
        rememberEDUState("unity.ncsu.edu", State.NORTH_CAROLINA);
        rememberEDUState("jeffco.edu", State.MISSISSIPPI);
        rememberEDUState("casa.sjsu.edu", State.CALIFORNIA);
        rememberEDUState("cornell-iowa.edu", State.IOWA);
        rememberEDUState("humboldt.edu", State.CALIFORNIA);
        rememberEDUState("evcc.ctc.edu", State.TEXAS);
        rememberEDUState("chabotcollege.edu", State.CALIFORNIA);
        rememberEDUState("bmc.edu", State.MISSISSIPPI);
        rememberEDUState("saintjoe.edu", State.INDIANA);
        rememberEDUState("health.usf.edu", State.FLORIDA);
        rememberEDUState("saclink.csus.edu", State.CALIFORNIA);
        rememberEDUState("kc.edu", State.OHIO);
        rememberEDUState("swcaz.edu", State.UNKNOWN);    // bad
        rememberEDUState("pobox.upenn.edu", State.PENNSYLVANIA);
        rememberEDUState("marywood.edu", State.PENNSYLVANIA);
        rememberEDUState("fmarion.edu", State.SOUTH_CAROLINA);
        rememberEDUState("warnerpacific.edu", State.OREGON);
        rememberEDUState("widener.edu", State.PENNSYLVANIA);
        rememberEDUState("utoledo.edu", State.OHIO);
        rememberEDUState("cookman.edu", State.FLORIDA);
        rememberEDUState("oregon.uoregon.edu", State.OREGON);
        rememberEDUState("gordon.edu", State.MASSACHUSETTS);
        rememberEDUState("tabor.edu", State.KANSAS);
        rememberEDUState("mail.unomaha.edu", State.NEBRASKA);
        rememberEDUState("guilford.edu", State.NORTH_CAROLINA);
        rememberEDUState("doane.edu", State.NEBRASKA);
        rememberEDUState("grizzlies.adams.edu", State.COLORADO);
        rememberEDUState("hutchcc.edu", State.KANSAS);
        rememberEDUState("po.cwru.edu", State.OHIO);
        rememberEDUState("cochise.edu", State.ARIZONA);
        rememberEDUState("oru.edu", State.OKLAHOMA);
        rememberEDUState("mail.pdx.edu", State.OREGON);
        rememberEDUState("uiuc.edu", State.ILLINOIS);
        rememberEDUState("pnca.edu", State.OREGON);
        rememberEDUState("andrew.cmu.edu", State.PENNSYLVANIA);
        rememberEDUState("jccmi.edu", State.MICHIGAN);
        rememberEDUState("oc.ctc.edu", State.TEXAS);
        rememberEDUState("peninsula.wednet.edu", State.WASHINGTON);
        rememberEDUState("ius.edu", State.INDIANA);
        rememberEDUState("eou.edu", State.OREGON);
        rememberEDUState("maxwell.syr.edu", State.NEW_YORK);
        rememberEDUState("nyts.edu", State.NEW_YORK);
        rememberEDUState("smcc.edu", State.MISSISSIPPI);
        rememberEDUState("elmira.edu", State.NEW_YORK);
        rememberEDUState("sccmail.maricopa.edu", State.ARIZONA);
        rememberEDUState("colled.msstate.edu", State.MISSISSIPPI);
        rememberEDUState("mail.mcneese.edu", State.LOUISIANA);
        rememberEDUState("usouthal.edu", State.ALABAMA);
        rememberEDUState("linnbenton.edu", State.OREGON);
        rememberEDUState("hartnell.edu", State.CALIFORNIA);
        rememberEDUState("colby-sawyer.edu", State.NEW_HAMPSHIRE);
        rememberEDUState("hsc.edu", State.VIRGINIA);
        rememberEDUState("sksm.edu", State.CALIFORNIA);
        rememberEDUState("esmail.mcc.edu", State.MICHIGAN);
        rememberEDUState("mercersburg.edu", State.PENNSYLVANIA);
        rememberEDUState("merrimack.edu", State.MASSACHUSETTS);
        rememberEDUState("tamu.edu", State.TEXAS);
        rememberEDUState("collin.edu", State.TEXAS);
        rememberEDUState("udel.edu", State.DELAWARE);
        rememberEDUState("gu.gonzaga.edu", State.WASHINGTON);
        rememberEDUState("uvawise.edu", State.VIRGINIA);
        rememberEDUState("centralia.ctc.edu", State.WASHINGTON);
        rememberEDUState("semo.edu", State.MISSOURI);
        rememberEDUState("sunstroke.sdsu.edu", State.CALIFORNIA);
        rememberEDUState("unt.edu", State.TEXAS);
        rememberEDUState("mail.wtamu.edu", State.TEXAS);
        rememberEDUState("college.ucla.edu", State.CALIFORNIA);
        rememberEDUState("umary.edu", State.MARYLAND);
        rememberEDUState("edgecombe.edu", State.NORTH_CAROLINA);
        rememberEDUState("mail.ifas.ufl.edu", State.FLORIDA);
        rememberEDUState("u.brockport.edu", State.NEW_YORK);
        rememberEDUState("po-box.esu.edu", State.PENNSYLVANIA);
        rememberEDUState("scmail.spelman.edu", State.GEORGIA);
        rememberEDUState("twcnet.edu", State.TENNESSEE);
        rememberEDUState("uaf.edu", State.ALASKA);
        rememberEDUState("csuhayward.edu", State.CALIFORNIA);
        rememberEDUState("monm.edu", State.ILLINOIS);
        rememberEDUState("muskingum.edu", State.OHIO);
        rememberEDUState("ivcc.edu", State.ILLINOIS);
        rememberEDUState("saonet.ucla.edu", State.CALIFORNIA);
        rememberEDUState("cba.ufl.edu", State.FLORIDA);
        rememberEDUState("hastings.edu", State.NEBRASKA);
        rememberEDUState("exchange.colostate.edu", State.COLORADO);
        rememberEDUState("utep.edu", State.TEXAS);
        rememberEDUState("mccormick.edu", State.ILLINOIS);
        rememberEDUState("mtholyoke.edu", State.MASSACHUSETTS);
        rememberEDUState("lagcc.cuny.edu", State.NEW_YORK);
        rememberEDUState("med.cornell.edu", State.NEW_YORK);
        rememberEDUState("alum.mit.edu", State.MASSACHUSETTS);
        rememberEDUState("columbiasc.edu", State.SOUTH_CAROLINA);
        rememberEDUState("gwmail.gwu.edu", State.DISTRICT_OF_COLUMBIA);
        rememberEDUState("samuelmerritt.edu", State.CALIFORNIA);
        rememberEDUState("email.wofford.edu", State.SOUTH_CAROLINA);
        rememberEDUState("kcai.edu", State.MISSOURI);
        rememberEDUState("sru.edu", State.PENNSYLVANIA);
        rememberEDUState("gwm.sc.edu", State.SOUTH_CAROLINA);
        rememberEDUState("ivc.edu", State.CALIFORNIA);
        rememberEDUState("grinnell.edu", State.IOWA);
        rememberEDUState("matc.edu", State.WISCONSIN);
        rememberEDUState("certauth.cc.wmich.edu", State.MICHIGAN);
        rememberEDUState("nsuok.edu", State.OKLAHOMA);
        rememberEDUState("alb.edu", State.UNKNOWN);           // bad
        rememberEDUState("marianuniversity.edu", State.WISCONSIN);
        rememberEDUState("sacredheart.edu", State.CONNECTICUT);
        rememberEDUState("my.twcnet.edu", State.TENNESSEE);
        rememberEDUState("mail.msj.edu", State.OHIO);
        rememberEDUState("eckerd.edu", State.FLORIDA);
        rememberEDUState("csc.edu", State.NEBRASKA);
        rememberEDUState("maricopa.edu", State.ARIZONA);
        rememberEDUState("aum.edu", State.ALABAMA);
        rememberEDUState("bgnet.bgsu.edu", State.OHIO);
        rememberEDUState("northern.edu",State.SOUTH_DAKOTA);
        rememberEDUState("loras.edu",State.IOWA);
        rememberEDUState("usfca.edu",State.CALIFORNIA);
        rememberEDUState("greenmtn.edu",State.VERMONT);
        rememberEDUState("ncf.edu",State.FLORIDA);
        rememberEDUState("nau.edu",State.ARIZONA);
        rememberEDUState("lehigh.edu",State.PENNSYLVANIA);
        rememberEDUState("fhsu.edu",State.KANSAS);
        rememberEDUState("csusm.edu",State.CALIFORNIA);
        rememberEDUState("wayne.edu",State.MICHIGAN);
        rememberEDUState("udmercy.edu",State.MICHIGAN);
        rememberEDUState("marygrove.edu",State.MICHIGAN);
        rememberEDUState("daemen.edu",State.NEW_YORK);
        rememberEDUState("depauw.edu",State.INDIANA);
        rememberEDUState("fredonia.edu",State.NEW_YORK);
          rememberEDUState("linfield.edu",State.OREGON);
        rememberEDUState("lasell.edu",State.MASSACHUSETTS);
        rememberEDUState("moreheadstate.edu",State.KENTUCKY);
        rememberEDUState("umaryland.edu",State.MARYLAND);
        rememberEDUState("hope.edu",State.MICHIGAN);
        rememberEDUState("muohio.edu",State.OHIO);
        rememberEDUState("ndc.edu",State.OHIO);
        rememberEDUState("swcaz.edu",State.ARIZONA);
        rememberEDUState("iastate.edu",State.IOWA);
        rememberEDUState("calu.edu",State.PENNSYLVANIA);
        rememberEDUState("oneonta.edu",State.NEW_YORK);
        rememberEDUState("trinitydc.edu",State.DISTRICT_OF_COLUMBIA);
        rememberEDUState("neumann.edu",State.PENNSYLVANIA);
        rememberEDUState("hpu.edu",State.HAWAII);
        rememberEDUState("dyc.edu",State.NEW_YORK);
        rememberEDUState("miad.edu",State.WISCONSIN);
        rememberEDUState("bc3.edu",State.PENNSYLVANIA);
        rememberEDUState("cbts.edu",State.KANSAS);
        rememberEDUState("hiram.edu",State.OHIO);
        rememberEDUState("enmu.edu",State.NEW_MEXICO);
        rememberEDUState("plattsburgh.edu",State.NEW_YORK);
        rememberEDUState("webster.edu",State.MISSOURI);
        rememberEDUState("castleton.edu",State.VERMONT);
        rememberEDUState("uindy.edu",State.INDIANA);
        rememberEDUState("miamioh.edu",State.OHIO);
        rememberEDUState("marlboro.edu",State.VERMONT);
     //   rememberEDUState("huhezi.edu",State.u);
        rememberEDUState("polyu.edu",State.NEW_YORK);
        rememberEDUState("uwimona.edu",State.OVERSEAS);
        rememberEDUState("cobleskill.edu",State.NEW_YORK);
        rememberEDUState("lindsey.edu",State.KENTUCKY);
        rememberEDUState("sunyjefferson.edu",State.NEW_YORK);
        rememberEDUState("westmont.edu",State.CALIFORNIA);
        rememberEDUState("calstate.edu",State.CALIFORNIA);
        rememberEDUState("oldwestbury.edu",State.NEW_YORK);
        rememberEDUState("stjohns.edu",State.NEW_YORK);
        rememberEDUState("alvernia.edu",State.PENNSYLVANIA);
        rememberEDUState("cottey.edu",State.MISSOURI);
        rememberEDUState("duq.edu",State.PENNSYLVANIA);
        rememberEDUState("simpson.edu",State.IOWA);
        rememberEDUState("siena.edu",State.NEW_YORK);
        rememberEDUState("purchase.edu",State.NEW_YORK);
        rememberEDUState("troy.edu",State.ALABAMA);
        rememberEDUState("losrios.edu",State.CALIFORNIA);
        rememberEDUState("middlebury.edu",State.VERMONT);
          rememberEDUState("thomas.edu",State.MAINE);
        rememberEDUState("lanecollege.edu",State.TENNESSEE);
         rememberEDUState("wpi.edu",State.MASSACHUSETTS);
        rememberEDUState("ucmerced.edu",State.CALIFORNIA);
        rememberEDUState("maryvillecollege.edu",State.TENNESSEE);
        rememberEDUState("berry.edu",State.GEORGIA);
        //  rememberEDUState("aii.edu",State.Unknown);
        rememberEDUState("pitzer.edu",State.CALIFORNIA);
        rememberEDUState("delhi.edu",State.NEW_YORK);
        rememberEDUState("evansville.edu",State.INDIANA);
        rememberEDUState("mclennan.edu",State.TEXAS);
        rememberEDUState("wichita.edu",State.KANSAS);
        rememberEDUState("csmd.edu",State.MARYLAND);
        rememberEDUState("wabash.edu",State.INDIANA);
        rememberEDUState("binghamton.edu",State.NEW_YORK);
        rememberEDUState("scsu.edu",State.SOUTH_CAROLINA);
        rememberEDUState("umassd.edu",State.MASSACHUSETTS);
        rememberEDUState("apsu.edu",State.TENNESSEE);
    //    rememberEDUState("cccoes.edu",State.Unknown);
        rememberEDUState("oswego.edu",State.NEW_YORK);
        rememberEDUState("wooster.edu",State.OHIO);
      //  rememberEDUState("uophx.edu",State.Unknown);
        rememberEDUState("albany.edu",State.NEW_YORK);
        rememberEDUState("kirkwood.edu",State.IOWA);
        rememberEDUState("prescott.edu",State.ARIZONA);
        rememberEDUState("dowling.edu",State.NEW_YORK);
        rememberEDUState("sau.edu",State.IOWA);
        rememberEDUState("earlham.edu",State.INDIANA);
        rememberEDUState("scu.edu",State.CALIFORNIA);
        rememberEDUState("brandeis.edu",State.MASSACHUSETTS);
        rememberEDUState("ilstu.edu",State.ILLINOIS);
        rememberEDUState("morrisville.edu",State.NEW_YORK);
         rememberEDUState("appstate.edu",State.NORTH_CAROLINA);
        rememberEDUState("wright.edu",State.OHIO);
        rememberEDUState("nhcc.edu",State.MINNESOTA);
        rememberEDUState("albertus.edu",State.CONNECTICUT);
        rememberEDUState("jcu.edu",State.OHIO);
        rememberEDUState("alma.edu",State.MICHIGAN);
        rememberEDUState("lasc.edu",State.CALIFORNIA);
        rememberEDUState("slu.edu",State.MISSOURI);
        rememberEDUState("cua.edu",State.DISTRICT_OF_COLUMBIA);
        rememberEDUState("utm.edu",State.TENNESSEE);
        rememberEDUState("sussex.edu",State.NEW_JERSEY);
        rememberEDUState("iun.edu",State.INDIANA);
        rememberEDUState("calpoly.edu",State.CALIFORNIA);
        rememberEDUState("wcccd.edu",State.MICHIGAN);
        rememberEDUState("antioch.edu",State.CALIFORNIA);
        rememberEDUState("bates.edu",State.MAINE);
        rememberEDUState("sunyorange.edu",State.NEW_YORK);
        rememberEDUState("whittier.edu",State.CALIFORNIA);
        rememberEDUState("wfu.edu",State.NORTH_CAROLINA);
      //  rememberEDUState("naicu.edu",State.Unknown);
        rememberEDUState("rider.edu",State.NEW_JERSEY);
    }


    public static State getEmailState(String email) {
        buildEdyByState();

        State ret = eduByState.get(email);
        if(ret != null)
            return ret;
        String domain = getDomain(email);
        if (!domain.equalsIgnoreCase(email))
            ret = eduByState.get(email);
        if(ret != null)
            return ret;
        return State.UNKNOWN;
    }
}
